### ISSUE TITLE
OPUS files not being tagged, even when converted from tagged files.

### ISSUE THREAD

**Issue by rinfythegypsy** [gchudov/cuetools.net#145]
[https://hydrogenaud.io/index.php?topic=121768.0](https://hydrogenaud.io/index.php?topic=121768.0)

**Comment by ha-korth** [comment]
valid link https://hydrogenaud.io/index.php?topic=121768.0
Files are being tagged but the encoded file is damaged when tags are written.
Also there are issues with OpusPictureTag (METADATA_BLOCK_PICTURE 

- ::description problem when full URL added `(e.g. http://coverartarchive.org/release/...jpg)`
- width x height added to ::description instead of ::width and ::height 

https://opus-codec.org/docs/opusfile_api-0.7/structOpusPictureTag.html

**Comment by c72578** [comment]
@rinfythegypsy thanks for this bug report about tagging of opus files.
CUETools uses taglib-sharp for tagging the files. There is an upstream fix in the main branch concerning corrupting OPUS files on write:
https://github.com/mono/taglib-sharp/pull/232
https://github.com/mono/taglib-sharp/commit/0244c30b7686c1c40543cd4127c8d497f5c3a635

I have started updating the taglib-sharp version used in CUETools, which will include this fix.

**Comment by c72578** [comment]
@rinfythegypsy a build for testing CUETools with updated taglib-sharp can be downloaded from here:
https://github.com/gchudov/cuetools.net/pull/147#issuecomment-985784082

The following message does not show up anymore, when running opusinfo:
`Negative or zero granulepos (0) on Opus stream outside of headers. This file was created by a buggy encoder`
