### ISSUE TITLE
CUETools - wrong 'cover type' in embedded art

### ISSUE THREAD

**Issue by ha-korth** [gchudov/cuetools.net#146]
Vorbis (METADATA_BLOCK_PICTURE)
FLAC, OPUS (maybe other formats) have wrong 'cover type' applied to embedded art when retrieved from CTDB. 

'cover type' should be `3` for `Cover (front)` but has `255` instead.
CUERipper applies the 'cover type' as `3.`

Also noticed that (width x height) is added to the description but not to `width of the picture in pixels` and `height of the picture in pixels` sections.

**Comment by c72578** [comment]
@ha-korth Thanks for this report.
So far, I could not reproduce the issue in CUETools 2.1.9 or 2.2.0.
I did the following tests so far:
- Rip a CD using CUERipper without any album art.
- Convert this ripped disc using CUETools to flac (cuetools, tracks, 5)
- Retrieve album art using CTDB and embed album art
- Extract the tag info from the created flac files using metaflac
- The result is the following_

```
METADATA block #3
  type: 6 (PICTURE)
  is last: false
  length: 14565
  type: 3 (Cover (front))
  MIME type: image/jpeg
```

Further tests were also carried out, when album art was already embedded from CUERipper or in a local folder.jpg. No difference, the result has always been `type: 3 (Cover (front))` so far, after converting with CUETools and retrieving the cover art from CTDB.

Maybe you have got additional information, so that this issue can be reproduced.

**Comment by ha-korth** [comment]
I can reproduce in CUETools 2.1.9
Convert rip using CUETools to flac (libFLAC, tracks, 5)
Convert rip using CUETools to opus (opusenc, tracks, 128)
metaflac

```
METADATA block #3
type: 6 (PICTURE)
is last: false
length: 17051
type: 255 (UNDEFINED)
MIME type: image/jpeg
description: http://coverartarchive.org/release/3272d67e-3a6a-3c03-a6cb-184de816dd80/14011995629.jpg (1401x1384)
width: 0
height: 0
depth: 0
colors: 0 (unindexed)
data length: 16910
```

opusinfo

```
WARNING: Unknown picture type in METADATA_BLOCK_PICTURE comment 17 (stream 1): 255
         METADATA_BLOCK_PICTURE=255|image/jpeg|http://coverartarchive.org/release/3272d67e-3a6a-3c03-a6cb-184de816dd80/14011995629.jpg (1401x1384)|0x0x0|<16910 bytes of image data>
```

but can no longer reproduce with the test build for the taglib-sharp update or in 2.2.0 with the same sample rip. It may have been a glitch that was fixed with the taglib-sharp update. #147

metaflac

```
METADATA block #3
type: 6 (PICTURE)
is last: false
length: 17051
type: 3 (Cover (front))
MIME type: image/jpeg
description: http://coverartarchive.org/release/3272d67e-3a6a-3c03-a6cb-184de816dd80/14011995629.jpg (1401x1384)
width: 0
height: 0
depth: 0
colors: 0 (unindexed)
data length: 16910
```

opusinfo

`METADATA_BLOCK_PICTURE=3|image/jpeg|http://coverartarchive.org/release/3272d67e-3a6a-3c03-a6cb-184de816dd80/14011995629.jpg (1401x1384)|0x0x0|<16910 bytes of image data>`

I should probably close this.

**Comment by c72578** [comment]
@ha-korth thanks for checking.

Concerning:
> 
> Also noticed that (width x height) is added to the description but not to `width of the picture in pixels` and `height of the picture in pixels` sections.

There is the following (unresolved) upstream issue:
https://github.com/mono/taglib-sharp/issues/165

>
> ... when the file is saved and closed, looking in a hex editor, the Width, Height, ColorDepth, and IndexedColors properties (unique to TagLib.Flac.Picture) are saved to the file as 0.

Relevant code from TaglibSharp:
https://github.com/mono/taglib-sharp/blob/6a746346e80abdfc30d23237ebd2c360be1cb7fb/src/TaglibSharp/Flac/Picture.cs#L120

**Comment by c72578** [comment]
Additional info: In the meantime I have started updating `Flac/Picture.cs` of `taglib-sharp`.
The metadata will then look like this:
```
METADATA block #3
  type: 6 (PICTURE)
  is last: false
  length: 14570
  type: 3 (Cover (front))
  MIME type: image/jpeg
  description: http://coverartarchive.org/release/0deebcf9-7440-4268-8502-1d89eaabe272/1290648241.jpg (500x500)
  width: 300
  height: 300
  depth: 24
  ...
```
In this example, the default setting of CUETools `Tagging: Resize if resolution > 300` is used.

**Comment by c72578** [comment]
@ha-korth Could you please test this build, which contains a fix for `width` and `height`:
https://github.com/gchudov/cuetools.net/pull/165#issuecomment-1025218385

Needless to say, that the CUETools setting `Tagging - "Copy album art tags"` has to be unticked, in case of flac files with an already embedded album art and `width: 0, height: 0`, in order to get rid of it.

**Comment by ha-korth** [comment]
I set `Resize if resolution >` to 500
Both flac and opus show the height, width, and depth now
metaflac
```
METADATA block #3
  type: 6 (PICTURE)
  is last: false
  length: 39602
  type: 3 (Cover (front))
  MIME type: image/jpeg
  description: http://coverartarchive.org/release/3272d67e-3a6a-3c03-a6cb-184de816dd80/14011995629.jpg (1401x1384)
  width: 500
  height: 493
  depth: 24
  colors: 0 (unindexed)
  data length: 39461
```

opusinfo   `METADATA_BLOCK_PICTURE=3|image/jpeg|http://coverartarchive.org/release/3272d67e-3a6a-3c03-a6cb-184de816dd80/14011995629.jpg (1401x1384)|500x493x24|<39461 bytes of image data>`
