### ISSUE TITLE
Problems with "?" symbol in song name

### ISSUE THREAD

**Issue by CyberAndrew** [gchudov/cuetools.net#176]
When I convert this album:
https://nnmclub.to/forum/viewtopic.php?t=939153 -- Zемфира\Albums\2000 - Прости меня моя любовь
or https://rutracker.org/forum/viewtopic.php?t=2934880 -- 2000 - Прости меня моя любовь
in track-by-track flac conversion mode, I have problem with track 04.

It's name written in .cue as:
 TRACK 04 AUDIO
    TITLE "Хочешь?"
    PERFORMER "Zемфира"
    INDEX 01 09:57:65

But when it is converted, it has name
04. Хочешь_.flac

So, the "?" symbol is corrupted.

**Comment by CyberAndrew** [comment]
I am very sorry for being dumb, I found out that "?" symbol is forgotten in NTFS filenames.
There should be some pop-out window, that there was forbidden symbols that were replaced.

**Comment by c72578** [comment]
@CyberAndrew Thanks for your report.
Characters that are not allowed in file names are automatically replaced.
These are typically [1, 2]:
```
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

In order to avoid interruption of the process, the replacement in filenames is done automatically, without showing messages or windows. However, the original characters like `?` are available in the tags. Correct titles etc. can be displayed during playback.

[1] https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidfilenamechars?view=netframework-4.7
[2] https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names
