### ISSUE TITLE
CUERipper 2.1.6 periodically scanning for metadata

### ISSUE THREAD

**Issue by HornetMaX** [gchudov/cuetools.net#20]
As described in [this](https://hydrogenaud.io/index.php/topic,117709.0.html) thread at HydrogenAudio 

I put a CD in, run CUERipper and I get a green progress bar in the lower right corner while CUERipper fetches the metadata; it finds it and all is fine.

The problem is that after a few seconds (~30 or so), it scans for it again, and then (after another 30s) again, and then again, no end. So if I manually edit the metadata, when it scans for it again I lose my changes.

It seems to have been already noticed in the past: [here](https://hydrogenaud.io/index.php/topic,66233.msg805782.html#msg805782)

**Comment by c72578** [comment]
Thanks for your report.
In the meantime I was able to reproduce the issue using an external USB CD drive (hp GT80N, FW R102) under Windows 10, using a build from current git master of CUETools (5f7b450b47e455a501b82b5e81308be168e4949f).
The described behavior of this issue occurred every now and then. Not that frequent as in your case, but after a few minutes the manually edited metadata was cleared.
Doing some debugging it turned out, that this is triggered by a `DBT_DEVNODES_CHANGED` event [1] coming from the operating system, which causes CUERipper to call `UpdateDrives()` and thereby clear the metadata. See:
https://github.com/gchudov/cuetools.net/blob/5f7b450b47e455a501b82b5e81308be168e4949f/CUERipper/frmCUERipper.cs#L218
Remarks:
- The `DBT_DEVNODES_CHANGED` event appeared without any user interaction. During the tests, CUERipper was just left open, with an inserted CD and after having edited some metadata. It was only the `DBT_DEVNODES_CHANGED` event, which occured (not `DBT_DEVICEARRIVAL` nor `DBT_DEVICEREMOVECOMPLETE`)
- For testing, these events can also be triggered on purpose by inserting or removing a USB stick, while CUERipper is running.

In order to avoid loosing any metadata, which has already been entered, I will prepare a PR, so that metadata will be saved using `data.selectedRelease.metadata.Save()` before clearing metatdata.

[1] https://docs.microsoft.com/en-us/windows/win32/devio/wm-devicechange

**Comment by c72578** [comment]
@HornetMaX it would be interesting to see, which device potentially causes `DBT_DEVNODES_CHANGE` events every ~30 s on your system.

You could run the attached tool HWDetect.exe from [1] in parallel to CUERipper in order to detect device change events, which cause clearing of the metadata:
[HwDetect_exe.zip](https://github.com/gchudov/cuetools.net/files/4454540/HwDetect_exe.zip)

On the test system here it looks like this:
![HWDetect_BT_mouse_disconnect_connect](https://user-images.githubusercontent.com/371551/78866525-d39c8500-7a3f-11ea-8b0a-d0d120419872.png)
Here, the BlueTooth mouse disconnects and reconnects and causes the `DBT_DEVNODES_CHANGE` events, which lead to clearing of the metadata in CUERipper.

A fix can be found in PR #50

[1] https://www.codeproject.com/Articles/14500/Detecting-Hardware-Insertion-and-or-Removal

**Comment by HornetMaX** [comment]
> @HornetMaX it would be interesting to see, which device potentially causes `DBT_DEVNODES_CHANGE` events every ~30 s on your system.
> 
> You could run the attached tool HWDetect.exe from [1] in parallel to CUERipper in order to detect device change events, which cause clearing of the metadata:
> [HwDetect_exe.zip](https://github.com/gchudov/cuetools.net/files/4454540/HwDetect_exe.zip)

Hi, thanks for looking into this.

The .exe doesn't run on my system (Win10): I have an error with missing dlls (MFC71.DLL, MSVCR71.DLL). Weird as I do have 2010 Redist x86 & x64 installed ....

**Comment by HornetMaX** [comment]
@c72578 nevermind, I downloaded the two dlls and dropped them in the forlder where I have HwDetect and it seems to run fine, but it doesn't report anything:

![cap](https://user-images.githubusercontent.com/12623200/78873732-9b02a880-7a4b-11ea-89b8-a3d3fc558800.png)

**Comment by c72578** [comment]
@HornetMaX OK, thanks for checking. And I guess CUERipper was still clearing metadata every ~30s while HwDetect.exe was running.

Could you please also test the attached program "Device insertion monitor", while CUERipper is running and metadata gets cleared by CUERipper?
[device_insertion_monitor_wms.zip](https://github.com/gchudov/cuetools.net/files/4455422/device_insertion_monitor_wms.zip)

Remark: This tool has been compiled using the source code from here:
http://www.rohitab.com/discuss/topic/41757-device-media-insertion-monitor/page-2#entry10100874

**Comment by HornetMaX** [comment]
> @HornetMaX OK, thanks for checking. And I guess CUERipper was still clearing metadata every ~30s while HwDetect.exe was running.

Right, metadata got cleared, nothing reported by HwDetect.
 
> Could you please also test the attached program "Device insertion monitor", while CUERipper is running and metadata gets cleared by CUERipper?
> [device_insertion_monitor_wms.zip](https://github.com/gchudov/cuetools.net/files/4455453/device_insertion_monitor_wms.zip)
> 
> Remark: This tool has been compiled using the source code from here:
> http://www.rohitab.com/discuss/topic/41757-device-media-insertion-monitor/page-2#entry10100874

Just tried. It detects a device type "CD/DVD" (no other info) when I insert a CD (guess thats OK :) ), but nothing else when metadata gets cleared.

**Comment by c72578** [comment]
@HornetMaX Thanks again for checking.
Could you please test the attached build from PR #50 (commit 1ee04d3c7a94312a7343b2e5d44a6f9a1f50d84a) and check, if the manually edited metadata gets saved and you do not loose it any more every ~30s?
[CUETools_2.1.7_2020-04-10_git_PR50.zip](https://github.com/gchudov/cuetools.net/files/4461627/CUETools_2.1.7_2020-04-10_git_PR50.zip)

**Comment by HornetMaX** [comment]
> @HornetMaX Thanks again for checking.
> Could you please test the attached build from PR #50 (commit [1ee04d3](https://github.com/gchudov/cuetools.net/commit/1ee04d3c7a94312a7343b2e5d44a6f9a1f50d84a)) and check, if the manually edited metadata gets saved and you do not loose it any more every ~30s?
> [CUETools_2.1.7_2020-04-10_git_PR50.zip](https://github.com/gchudov/cuetools.net/files/4461627/CUETools_2.1.7_2020-04-10_git_PR50.zip)

Hi, it stills perodically connect to external sources to fetch covers and so on, but manually edited metadata does not get reset, so that's much better !

**Comment by c72578** [comment]
@HornetMaX OK, thanks for testing.
Concerning the periodical events, which occur ~30s:
Could you please run the following program [1], while CUERipper is running and see what it reports every time, when CUERipper periodically connects to external sources.
[pnpmon.zip](https://github.com/gchudov/cuetools.net/files/4464153/pnpmon.zip)
- Start PnPMon
- Click the Notifications > Device menu option to start receiving device notifications

What I observed on the system here during further testing is, that also devices on the network, which appear or disappear cause `DBT_DEVNODES_CHANGED` events.

The goal would be to ignore `DBT_DEVNODES_CHANGED` events, which are not relevant to CUERipper and only react on changes concerning e.g. CD drives.

[1]  Plug-and-Play Monitor Version 2.1, from http://noeld.com/programs.asp?cat=misc#pnpmon

**Comment by HornetMaX** [comment]
Holy crap, that worked !! It's my tv (it's on the network indeed):

> 2020/04/11 10:51:42.468 - Device notifications enabled.
2020/04/11 10:52:49.769 - DBT_DEVICEREMOVECOMPLETE
                            Device path: \\?\SWD#DAFUPnPProvider#uuid:dd47e236-1d51-44b5-8d91-c4f3344ffabc#{2a323d9d-edf1-430b-ab95-5860894493d4}
                              Friendly Name: KD-55XE9005
                              Description: Generic software device
                              Manufacturer: Sony Corporation
                              Device Setup Class: Software devices (SoftwareDevice)
2020/04/11 10:52:49.787 - DBT_DEVICEREMOVECOMPLETE
                            Device path: \\?\SWD#DAFUPnPProvider#uuid:dd47e236-1d51-44b5-8d91-c4f3344ffabc#{ac4630a5-0b64-46e5-981b-12535fc1f5de}
                              Friendly Name: KD-55XE9005
                              Description: Generic software device
                              Manufacturer: Sony Corporation
                              Device Setup Class: Software devices (SoftwareDevice)
2020/04/11 10:52:49.802 - DBT_DEVICEREMOVECOMPLETE
                            Device path: \\?\SWD#DAFUPnPProvider#uuid:dd47e236-1d51-44b5-8d91-c4f3344ffabc#{1dc7cf2a-9167-5887-b1b2-16e04384f64c}
                              Friendly Name: KD-55XE9005
                              Description: Generic software device
                              Manufacturer: Sony Corporation
                              Device Setup Class: Software devices (SoftwareDevice)
2020/04/11 10:52:49.818 - DBT_DEVNODES_CHANGED
2020/04/11 10:52:51.719 - DBT_DEVICEARRIVAL
                            Device path: \\?\SWD#DAFUPnPProvider#uuid:dd47e236-1d51-44b5-8d91-c4f3344ffabc#{2a323d9d-edf1-430b-ab95-5860894493d4}
                              Friendly Name: KD-55XE9005
                              Description: Generic software device
                              Manufacturer: Sony Corporation
                              Device Setup Class: Software devices (SoftwareDevice)
2020/04/11 10:52:51.733 - DBT_DEVICEARRIVAL
                            Device path: \\?\SWD#DAFUPnPProvider#uuid:dd47e236-1d51-44b5-8d91-c4f3344ffabc#{ac4630a5-0b64-46e5-981b-12535fc1f5de}
                              Friendly Name: KD-55XE9005
                              Description: Generic software device
                              Manufacturer: Sony Corporation
                              Device Setup Class: Software devices (SoftwareDevice)
2020/04/11 10:52:51.750 - DBT_DEVICEARRIVAL
                            Device path: \\?\SWD#DAFUPnPProvider#uuid:dd47e236-1d51-44b5-8d91-c4f3344ffabc#{1dc7cf2a-9167-5887-b1b2-16e04384f64c}
                              Friendly Name: KD-55XE9005
                              Description: Generic software device
                              Manufacturer: Sony Corporation
                              Device Setup Class: Software devices (SoftwareDevice)
2020/04/11 10:52:51.766 - DBT_DEVNODES_CHANGED
