### ISSUE TITLE
Update libFLAC to 1.4.1

### ISSUE THREAD

**Issue by c72578** [gchudov/cuetools.net#217]
Edit: FLAC 1.4.1 has been released on 2022-09-22.
https://github.com/xiph/flac/releases/tag/1.4.1

FLAC 1.4.0 has been released on 2022-09-09.
https://github.com/xiph/flac/releases/tag/1.4.0

The version used in CUETools is currently `1.3.4` and will be updated for the next release.

If desired, CUETools `plugins\x64\libFLAC_dynamic.dll` can be updated to `1.4.0` in the meantime from:
- Official FLAC release:
https://github.com/xiph/flac/releases/download/1.4.0/flac-1.4.0-win.zip
Remark: Use `flac-1.4.0-win\Win64\libFLAC.dll` and rename it to `plugins\x64\libFLAC_dynamic.dll`
- RareWares:
https://www.rarewares.org/lossless.php#flac-dll
Direct download link:
https://www.rarewares.org/files/lossless/flac_dll-1.4.0-x64.zip
The file name of the dll is already OK: `libFLAC_dynamic.dll`

**Comment by Barough** [comment]
I recommend to use this set of of v1.4.0 since the official release isn't linked so a dependence to external dll's is required. :(

John's Intel 19.2 Compiles  (RareWares)  :

FLAC v1.4.0 Binaries
http://www.rarewares.org/files/lossless/flac-1.4.0-x86-Intel-19.2.zip
http://www.rarewares.org/files/lossless/flac-1.4.0-x64-Intel-19.2.zip

FLAC v1.4.0 DLL's
http://www.rarewares.org/files/lossless/flac_dll-1.4.0-x86-nonXP-Intel-19.2.zip
http://www.rarewares.org/files/lossless/flac_dll-1.4.0-x64-Intel-19.2.zip

**Comment by Barough** [comment]
John's v1.4.1 Intel 19.2 Compiles (RareWares) :
https://www.rarewares.org/lossless.php

**Comment by guiweber** [comment]
@c72578 FLAC 1.4.2 was released shortly after 1.4.1, may be good to use that instead.

**Comment by Barough** [comment]
> @c72578 FLAC 1.4.2 was released shortly after 1.4.1, may be good to use that instead.

https://github.com/gchudov/cuetools.net/commit/a8588eb4fd97a48e70f1025d21058df52533e034
