### ISSUE TITLE
CUEripper: can't load ripper module

### ISSUE THREAD

**Issue by KRadiants** [gchudov/cuetools.net#338]
Ok so I already opened a thread yesterday, but because I didn't explain the actual issue I have, it got closed.

So when I launch CUEripper, it says that in the dropdown menu at the top. As i said in the last thread, I do have all plugins. However, the fix of unblocking the zip archive doesn't apply toe me, because it's not blocked. What other fix is there ?

**Comment by c72578** [comment]
@KRadiants Could you please post the path, where `CUETools_2.2.5.zip` has been unpacked to?
E.g.:
`D:\APPS\CUETools_2.2.5\`

**Comment by KRadiants** [comment]
On my SSD intenal drive, in the download folder, which is not the main one

**Comment by c72578** [comment]
> On my SSD intenal drive, in the download folder, which is not the main one

Please run the following command from Windows PowerShell:
```PowerShell
Get-ChildItem -Path "$($env:USERPROFILE)\Downloads\CUETools_2.2.5\" -Recurse | Unblock-File
```
Just in case there is a blocked file inside the `CUETools_2.2.5` directory, it will be unblocked.

**Comment by KRadiants** [comment]
Alright this worked, thanks

**Comment by freonpsandoz** [comment]
The description of the problem that I posted on the Hydrogenaudio forum was "Codecs missing after installing in Windows 11." I'm saying that here so that other people facing the same problem might have some chance of finding the solution with similar search terms. This problem only occurs in Windows 11, but there's absolutely no mention of that here. I also found that I needed to RUN POWERSHELL AS ADMINISTRATOR before this solution worked.
