### ISSUE TITLE
CUETools 2.1.6 loses ISRC on CUE files

### ISSUE THREAD

**Issue by JuniorJPDJ** [gchudov/cuetools.net#63]
When ISRC is specified on TRACK inside input CUE file, it's not specified on output CUE file TRACK

**Comment by c72578** [comment]
@JuniorJPDJ thanks for your bug report. This issue concerning ISRC has been fixed in master by the following commit: https://github.com/gchudov/cuetools.net/commit/9754a9a3282dd835e5544c618751c834e983fafc
See: https://github.com/gchudov/cuetools.net/blob/6fcd5b92d79e4db2c8e47fcfe7a410145f033a68/CUETools/frmChoice.cs#L185

**Comment by JuniorJPDJ** [comment]
When will new version be released?

**Comment by c72578** [comment]
@JuniorJPDJ A new release of CUETools is in preparation. Feel free to have a look: https://github.com/gchudov/cuetools.net/pull/81
